export const path = {
  PUBLIC_LAYOUT: "/",
  HOME: "",
  AO_DOI_TUYEN: "/ao-bong-da-doi-tuyen",
  AO_CLB: "/ao-bong-da-clb/",
  CLB: "/:slug",
  AO_KHONG_LOGO: "/ao-bong-da-khong-logo",
  BONG_DA: "/bong-da",
  PRODUCT_DEATAILS: "/product/:slug",
  CART: "/cart",
  CHECKOUT: "/checkout",
  BLOG: "/blog",
  LOGIN: "/login",
  REGISTER: "/register",
  NOTFOUND: "*",
};
