export const path = {
  PUBLIC_LAYOUT: "/",
  HOME: "",
  AO_DOI_TUYEN: "/ao-bong-da-doi-tuyen",
  AO_CLB: "/ao-bong-da-clb/",
  CLB: "/club/:slug",
  AO_KHONG_LOGO: "/ao-bong-da-khong-logo",
  BONG_DA: "/bong-da",
  PRODUCT_DEATAILS: "/product/:slug",
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDER_COMPLETE: "/orderComplete",
  SEARCH_PRODUCT: "/search/",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/changePassword",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  BLOG: "/blog",
  LOGIN: "/login",
  REGISTER: "/register",
  NOTFOUND: "*",
  WHISHLIST: "/whishList",
};
